Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 512
      Handler: activity.PutMatch
      CodeUri: /Users/onyeka/Documents/socialapp/socialappservice/lambdas/PutMatchLambda/PutMatchFunction
      Runtime: java11