Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 576
      Handler: activity.PutSwipe
      CodeUri: /Users/onyeka/Documents/socialapp/PutSwipeLambda/PutSwipeFunction
      Runtime: java11
