Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 256
      Handler: activity.App
      CodeUri: /Users/onyeka/Documents/socialapp/socialappservice/lambdas/PutUserProfileLambda/PutUserProfileFunction
      Runtime: java11