Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 576
      Handler: activity.App
      CodeUri: /Users/onyeka/Documents/socialapp/GetSwipeLambda/GetSwipeFunction
      Runtime: java11
