Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 512
      Handler: activity.GetUser
      CodeUri: /Users/onyeka/Documents/Final Year Project/SocialApps/socialappservice/src/lambdas/GetUserLambda/GetUserFunction
      Runtime: java11